server.port: 7000

app:
  product-service:
    host: localhost
    port: 7001
  recommendation-service:
    host: localhost
    port: 7002
  review-service:
    host: localhost
    port: 7003

logging:
  level:
    root: INFO
    se.magnus: DEBUG
  # Output to a file named application.log. 
#  file:
#    name: application.log
#    path: c:\APP  # Output to a file named spring.log in path /Users
  pattern:
    file: '%d{dd HH:mm:ss} [%thread] %-5level %logger{10}:%L - %msg%'  ## Logging pattern for file
---
spring.profiles: docker

server.port: 8080

app:
  product-service:
    host: product
    port: 8080
  recommendation-service:
    host: recommendation
    port: 8080
  review-service:
    host: review
    port: 8080